UPDATE "ShopCatalogItem"
SET
  "name" = data."name",
  "resource" = data."resource",
  "rankHint" = data."rankHint",
  "description" = data."description",
  "effect" = data."effect",
  "updatedAt" = CURRENT_TIMESTAMP
FROM (VALUES
  ('relique-tete-trois-faces', 'Partie 1/5 : tête à trois faces', 'Fragment 1/5', 'Relique unique', 'Tête à trois faces issue d''une idole incomplète, froide comme une prière interdite.', 'Fragment unique de relique. À réunir avec les autres parties.'),
  ('relique-buste-triangle-cercle', 'Partie 2/5 : buste avec triangle + cercle', 'Fragment 2/5', 'Relique unique', 'Buste gravé d''un triangle et d''un cercle, comme une géométrie rituelle impossible.', 'Fragment unique de relique. À réunir avec les autres parties.'),
  ('relique-bras-droit-xxx', 'Partie 3/5 : bras droit portant XXX', 'Fragment 3/5', 'Relique unique', 'Bras droit d''une statue ancienne, marqué du sigle XXX sur une surface usée.', 'Fragment unique de relique. À réunir avec les autres parties.'),
  ('relique-bras-gauche-globe', 'Partie 4/5 : bras gauche portant un globe', 'Fragment 4/5', 'Relique unique', 'Bras gauche serré autour d''un globe lisse, trop lourd pour sa taille.', 'Fragment unique de relique. À réunir avec les autres parties.'),
  ('relique-quatre-jambes', 'Partie 5/5 : quatre jambes', 'Fragment 5/5', 'Relique unique', 'Quatre jambes taillées dans une pierre sombre, base finale d''un assemblage rituel.', 'Fragment unique de relique. Complète la série des cinq parties.'),
  ('conte-ichibi', 'Conte Ichibi', 'Conte bijû', 'Archive unique', 'Rouleau narratif scellé autour de l''Ichibi, conservé dans une encre sableuse.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-nibi', 'Conte Nibi', 'Conte bijû', 'Archive unique', 'Conte aux marges bleutées, traversé par les traces du Nibi.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-sanbi', 'Conte Sanbi', 'Conte bijû', 'Archive unique', 'Récit humide et lourd, lié aux eaux profondes du Sanbi.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-yonbi', 'Conte Yonbi', 'Conte bijû', 'Archive unique', 'Conte rugueux, raturé de suie et de pierre, consacré au Yonbi.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-gobi', 'Conte Gobi', 'Conte bijû', 'Archive unique', 'Rouleau vif et nerveux, écrit comme une charge du Gobi.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-rokubi', 'Conte Rokubi', 'Conte bijû', 'Archive unique', 'Conte aux pages cireuses, marqué par la trace acide du Rokubi.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-nanabi', 'Conte Nanabi', 'Conte bijû', 'Archive unique', 'Rouleau léger, presque bruissant, dédié au Nanabi.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-hachibi', 'Conte Hachibi', 'Conte bijû', 'Archive unique', 'Conte ample et cadencé, bâti autour de la puissance du Hachibi.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-kyuubi', 'Conte Kyuubi', 'Conte bijû', 'Archive unique', 'Rouleau rouge, trop chaud au toucher, lié au Kyuubi.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-sage-senju', 'Conte Sage Senju', 'Conte sage', 'Archive unique', 'Conte ancien consacré au Sage Senju et à ses héritages.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-sage-uchiha', 'Conte Sage Uchiha', 'Conte sage', 'Archive unique', 'Conte scellé dans un papier noir, consacré au Sage Uchiha.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-sage-sarutobi', 'Conte Sage Sarutobi', 'Conte sage', 'Archive unique', 'Conte martial et rusé, consacré au Sage Sarutobi.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-sage-uzumaki', 'Conte Sage Uzumaki', 'Conte sage', 'Archive unique', 'Conte spiralé, chargé de sceaux, consacré au Sage Uzumaki.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('conte-sage-hyuga', 'Conte Sage Hyuga', 'Conte sage', 'Archive unique', 'Conte clair et précis, consacré au Sage Hyuga.', 'Objet de lore unique à conserver dans l''inventaire.'),
  ('bombe-fumigene', 'Bombe fumigène', 'Dissimulation', 'Consommable', 'Capsule noire remplie d''une poudre dense et sèche.', 'Compte comme une dissimulation de zone.'),
  ('bombe-aveuglante', 'Bombe aveuglante', 'Aveuglement', 'Consommable', 'Sphère striée qui libère un flash brutal et une pluie d''éclats lumineux.', 'Compte comme un aveuglement de zone, soit une immobilisation partielle.'),
  ('kit-soin', 'Kit de soin', 'Soin', 'Consommable', 'Trousse compacte de bandages, onguents et aiguilles de terrain.', 'Résorbe une blessure du rang du personnage.'),
  ('parchemin-explosif', 'Parchemin explosif', 'Explosion', 'Consommable', 'Étiquette de papier chargée d''une formule instable.', 'Compte comme une attaque de zone.'),
  ('chausse-trappes', 'Chausse-trappes', 'Entrave', 'Consommable', 'Poignée de pointes métalliques conçues pour verrouiller une trajectoire.', 'Compte comme une immobilisation de zone, soit une immobilisation partielle.'),
  ('sceau-alarme', 'Sceau d''alarme', 'Détection', 'Consommable', 'Bandelette de sceau qui vibre quand une présence trouble son périmètre.', 'Révèle les cibles dissimulées dans une zone.'),
  ('antidote-universel', 'Antidote universel', 'Antidote', 'Consommable', 'Fiole ambrée préparée pour les toxines les plus fréquentes.', 'Neutralise un empoisonnement du rang du personnage.'),
  ('stimulant-tetsujin', 'Stimulant Tetsujin', 'Stimulant', 'Usage RP unique', 'Dose métallique au goût amer, réservée aux efforts courts et violents.', 'Ajoute +1 action bonus le temps d''un tour, dans un seul RP.'),
  ('grigri-sablonneux', 'Grigri sablonneux', 'Taiyo no Chi', 'Protection durable', 'Talisman sec qui crisse même quand il n''y a pas de vent.', 'Permet de réaliser des RP à Taiyo no Chi sans craindre la Chaleur.'),
  ('dent-de-requin', 'Dent-de-Requin', 'Umi no Chi', 'Protection durable', 'Dent pâle montée sur cordelette, taillée comme un avertissement.', 'Permet de réaliser des RP à Umi no Chi sans craindre les super-prédateurs marins.'),
  ('tenue-militaire', 'Tenue Militaire', 'Hai no Chi', 'Protection durable', 'Tenue robuste, poussiéreuse, marquée par les codes des zones de conflit.', 'Permet de réaliser des RP à Hai no Chi sans craindre les assauts nomades.'),
  ('combinaison-hazmat', 'Combinaison Hazmat', 'Numa no Chi', 'Protection durable', 'Combinaison étanche, renforcée de coutures noires et de filtres lourds.', 'Permet de réaliser des RP à Numa no Chi sans craindre le poison.'),
  ('gantelet-shinobi', 'Gantelet Shinobi', 'Kekkei Genkai', 'Village C', 'Gantelet modulaire conçu pour accueillir des gestes techniques venus d''ailleurs.', 'Permet d''acheter une action d''un autre KG. La tarification associée prend en compte le +10 XP.'),
  ('mini-rouleaux-unique-durable-chargee', 'Mini-rouleaux shinobi : action unique/durable ou chargée', 'Action KG', 'Village C', 'Jeu de mini-rouleaux scellés pour techniques simples ou maintenues.', 'Support d''achat pour une action unique, durable ou chargée.'),
  ('mini-rouleaux-combinee-complexe', 'Mini-rouleaux shinobi : action combinée ou complexe', 'Action KG', 'Village C', 'Rouleaux doubles, ajustés pour des séquences plus exigeantes.', 'Support d''achat pour une action combinée ou complexe.'),
  ('mini-rouleaux-ultime', 'Mini-rouleaux shinobi : action ultime', 'Action KG', 'Village C', 'Rouleau court bordé d''un sceau plus dense que son format ne le laisse croire.', 'Support d''achat pour une action ultime.'),
  ('mini-rouleaux-supreme', 'Mini-rouleaux shinobi : action suprême', 'Action KG', 'Village C', 'Rouleau rare, fermé par un noeud sombre, réservé aux actions hors norme.', 'Support d''achat pour une action suprême.'),
  ('carte-isshin', 'Carte d''Isshin', 'Contrée étrangère', 'Renseignement', 'Carte annotée à la main, pleine de routes secondaires et de noms à demi effacés.', 'Permet d''apprendre plus d''informations contextuelles au sujet d''une Contrée étrangère.'),
  ('avis-recherche', 'Avis de recherche', 'La Troupe', 'Renseignement', 'Affiche froissée, complétée par une note confidentielle sous le portrait.', 'Donne une information sur un membre de la Troupe.'),
  ('lettre-cachetee-jdc', 'Lettre cachetée', 'Accès JDC', 'Trame unique', 'Lettre fermée par un cachet officiel, destinée à ouvrir un dossier sensible.', 'Donne accès au JDC.'),
  ('reduction-marchandises-vie', 'Réduction marchandises à vie', 'Boutique', 'Service permanent', 'Contrat discret, signé dans l''ombre du comptoir et difficile à renier.', 'Bénéficie de -25% de réduction sur toutes les marchandises à vie.'),
  ('reconquete-contree-300', 'Reconquête instantanée de Contrée - palier 300', 'Contrée perdue', 'Palier Reconquête 1', 'Ordre de mobilisation scellé pour reprendre rapidement un territoire perdu.', 'Permet de reconquérir instantanément une Contrée perdue.'),
  ('reconquete-contree-600', 'Reconquête instantanée de Contrée - palier 600', 'Contrée perdue', 'Palier Reconquête 2', 'Ordre de mobilisation renforcé pour une reconquête plus coûteuse.', 'Permet de reconquérir instantanément une Contrée perdue.'),
  ('reconquete-contree-900', 'Reconquête instantanée de Contrée - palier 900', 'Contrée perdue', 'Palier Reconquête 3', 'Ordre de campagne exigeant des ressources majeures.', 'Permet de reconquérir instantanément une Contrée perdue.'),
  ('reconquete-contree-1200', 'Reconquête instantanée de Contrée - palier 1200', 'Contrée perdue', 'Palier Reconquête 4', 'Ordre de campagne exceptionnel, réservé aux reconquêtes critiques.', 'Permet de reconquérir instantanément une Contrée perdue.'),
  ('jeton-reroll-ft', 'Jeton Reroll FT', 'Fiche technique', 'Service', 'Jeton gravé, échangeable contre une reprise encadrée de fiche technique.', 'Permet de demander un reroll FT.'),
  ('condition-rang-c-personnel', 'Supprimer une condition - Rang C personnel', 'Progression personnelle', 'Rang C', 'Cachet administratif qui simplifie une première étape personnelle de progression.', 'Supprime une condition pour atteindre un Rang C personnel.'),
  ('condition-rang-b-personnel', 'Supprimer une condition - Rang B personnel', 'Progression personnelle', 'Rang B', 'Cachet administratif qui simplifie une étape personnelle de progression.', 'Supprime une condition pour atteindre un Rang B personnel.'),
  ('condition-rang-a-personnel', 'Supprimer une condition - Rang A personnel', 'Progression personnelle', 'Rang A', 'Cachet administratif qui simplifie une étape personnelle de haut niveau.', 'Supprime une condition pour atteindre un Rang A personnel.'),
  ('condition-rang-s-personnel', 'Supprimer une condition - Rang S personnel', 'Progression personnelle', 'Rang S', 'Cachet rare, réservé aux ambitions personnelles les plus lourdes.', 'Supprime une condition pour atteindre un Rang S personnel.'),
  ('condition-rang-d-clanique', 'Supprimer une condition - Rang D clanique', 'Progression clanique', 'Rang D', 'Mandat de clan qui allège une condition communautaire interne.', 'Supprime une condition pour atteindre un Rang D clanique.'),
  ('condition-rang-c-clanique', 'Supprimer une condition - Rang C clanique', 'Progression clanique', 'Rang C', 'Mandat de clan qui allège une condition communautaire confirmée.', 'Supprime une condition pour atteindre un Rang C clanique.'),
  ('condition-rang-b-clanique', 'Supprimer une condition - Rang B clanique', 'Progression clanique', 'Rang B', 'Mandat de clan réservé aux objectifs structurants.', 'Supprime une condition pour atteindre un Rang B clanique.'),
  ('condition-rang-a-clanique', 'Supprimer une condition - Rang A clanique', 'Progression clanique', 'Rang A', 'Mandat de clan engageant des ressources majeures.', 'Supprime une condition pour atteindre un Rang A clanique.'),
  ('condition-rang-s-clanique', 'Supprimer une condition - Rang S clanique', 'Progression clanique', 'Rang S', 'Mandat de clan exceptionnel, scellé au plus haut niveau.', 'Supprime une condition pour atteindre un Rang S clanique.'),
  ('condition-rang-d-communautaire', 'Supprimer une condition - Rang D communautaire', 'Progression communautaire', 'Rang D', 'Ordre communautaire qui réduit une exigence collective.', 'Supprime une condition pour atteindre un Rang D communautaire.'),
  ('condition-rang-c-communautaire', 'Supprimer une condition - Rang C communautaire', 'Progression communautaire', 'Rang C', 'Ordre communautaire qui réduit une exigence collective avancée.', 'Supprime une condition pour atteindre un Rang C communautaire.'),
  ('condition-rang-b-communautaire', 'Supprimer une condition - Rang B communautaire', 'Progression communautaire', 'Rang B', 'Ordre communautaire mobilisant des ressources importantes.', 'Supprime une condition pour atteindre un Rang B communautaire.'),
  ('condition-rang-a-communautaire', 'Supprimer une condition - Rang A communautaire', 'Progression communautaire', 'Rang A', 'Ordre communautaire d''ampleur régionale.', 'Supprime une condition pour atteindre un Rang A communautaire.'),
  ('condition-rang-s-communautaire', 'Supprimer une condition - Rang S communautaire', 'Progression communautaire', 'Rang S', 'Ordre communautaire exceptionnel, presque politique.', 'Supprime une condition pour atteindre un Rang S communautaire.'),
  ('promotion-chunin', 'Promotion automatique au grade Chunin', 'Grade', 'Promotion', 'Dossier de promotion accélérée, validé par tampon officiel.', 'Accorde une promotion automatique au grade Chunin.'),
  ('promotion-jonin', 'Promotion automatique au grade Jonin', 'Grade', 'Promotion', 'Dossier de promotion avancée, réservé aux shinobi déjà confirmés.', 'Accorde une promotion automatique au grade Jonin.'),
  ('changer-bonus-genin', 'Changer de bonus Genin', 'Bonus de grade', 'Genin', 'Formulaire court pour ajuster un avantage de début de parcours.', 'Permet de changer de bonus Genin.'),
  ('changer-bonus-chunin', 'Changer de bonus Chunin', 'Bonus de grade', 'Chunin', 'Formulaire de révision pour un avantage intermédiaire.', 'Permet de changer de bonus Chunin.'),
  ('changer-bonus-jonin', 'Changer de bonus Jonin', 'Bonus de grade', 'Jonin', 'Formulaire de révision pour un avantage avancé.', 'Permet de changer de bonus Jonin.'),
  ('changer-bonus-sannin', 'Changer de bonus Sannin', 'Bonus de grade', 'Sannin', 'Formulaire rare, réservé aux profils d''exception.', 'Permet de changer de bonus Sannin.'),
  ('mutation-corps-special', 'Mutation dans un autre Corps Spécial', 'Corps Spécial', 'Grade conservé', 'Ordre de mutation qui déplace l''affectation sans casser le grade.', 'Permet une mutation dans un autre Corps Spécial en conservant ton Grade.'),
  ('cadeau-mystere', 'Achat d''un cadeau mystère', 'Surprise', 'Mystère', 'Boîte scellée, étiquette absente, promesse incertaine.', 'Permet d''acheter un cadeau mystère.'),
  ('titre-personnalise', 'Soumettre un Titre personnalisé', 'Titre', 'Cosmétique', 'Plaque vierge destinée à recevoir un titre officiel ou cérémoniel.', 'Permet de soumettre un Titre personnalisé.'),
  ('reroll-trame', 'Reroll de Trame', 'Trame', 'Service narratif', 'Bobine noire que l''on coupe pour relancer une trajectoire narrative.', 'Permet de demander un reroll de Trame.'),
  ('pnj-itinerant', 'Apparition de PNJ itinérant', 'PNJ', 'Service narratif', 'Jeton de convocation pour attirer une présence de passage au bon endroit.', 'Permet de provoquer l''apparition d''un PNJ itinérant.')
) AS data("itemKey", "name", "resource", "rankHint", "description", "effect")
WHERE "ShopCatalogItem"."itemKey" = data."itemKey";
